# This file was generated by GoReleaser. DO NOT EDIT.
cask "dol" do
  name "dol"
  desc "Detect dark/light mode on the CLI"
  homepage "https://github.com/netmute/dol"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dol"

  on_macos do
    on_intel do
      url "https://github.com/netmute/dol/releases/download/v#{version}/dol_Darwin_x86_64.tar.gz"
      sha256 "54b29b46a9afd83aa1655375c2c6d8801397f988f98504abbb530fe65a553df9"
    end
    on_arm do
      url "https://github.com/netmute/dol/releases/download/v#{version}/dol_Darwin_arm64.tar.gz"
      sha256 "f1bd477302ea37f5e2d320a41b9860e8c6e078999647e90af65a55f1b20a1ef2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/netmute/dol/releases/download/v#{version}/dol_Linux_x86_64.tar.gz"
      sha256 "58668f368d0f7548f50f6bb16f964e1227a7a2561f51b7170295ec57ed9e00c1"
    end
    on_arm do
      url "https://github.com/netmute/dol/releases/download/v#{version}/dol_Linux_arm64.tar.gz"
      sha256 "dbcfba9effd29c16f92620a5e4a91af5aa9df890a35e7285e464ba3fa8062109"
    end
  end

  # No zap stanza required
end
