# This file was generated by GoReleaser. DO NOT EDIT.
cask "dol" do
  name "dol"
  desc ""
  homepage ""
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dol"

  on_macos do
    on_intel do
      url "https://github.com/netmute/dol/releases/download/v#{version}/dol_Darwin_x86_64.tar.gz"
      sha256 "3aad3974023d05f56508a3a09f55f0eeb707ef55a373355e87c0adbc523ece80"
    end
    on_arm do
      url "https://github.com/netmute/dol/releases/download/v#{version}/dol_Darwin_arm64.tar.gz"
      sha256 "a92e8d814976d7ba5df15e8540d381d193aa48d140a100681d4f41045f854384"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/netmute/dol/releases/download/v#{version}/dol_Linux_x86_64.tar.gz"
      sha256 "f80090eab7bf1d8f0111cd5359b992422251680c6b857d54a5bc9b812c78d8d1"
    end
    on_arm do
      url "https://github.com/netmute/dol/releases/download/v#{version}/dol_Linux_arm64.tar.gz"
      sha256 "22bfd66c83e352d2dc3a9b1a146762a9fbe34fcbca678720a9526c1624e92879"
    end
  end

  # No zap stanza required
end
