# This file was generated by GoReleaser. DO NOT EDIT.
cask "dol" do
  name "dol"
  desc "Detect dark/light mode on the CLI"
  homepage "https://github.com/netmute/dol"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dol"

  on_macos do
    on_intel do
      url "https://github.com/netmute/dol/releases/download/v#{version}/dol_Darwin_x86_64.tar.gz"
      sha256 "a036b959dbed22f941802bbcf274995cd01dc266472276d6e4cd48bc542a08ad"
    end
    on_arm do
      url "https://github.com/netmute/dol/releases/download/v#{version}/dol_Darwin_arm64.tar.gz"
      sha256 "dee338b892c49bacc338f5330820956b4795656cb83c39dbe57d902cc1f5b5bf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/netmute/dol/releases/download/v#{version}/dol_Linux_x86_64.tar.gz"
      sha256 "f32b1313f6f4aacc741335e1ec7042c79e7ac4e3d3578beaceeaf5c9727aa9a0"
    end
    on_arm do
      url "https://github.com/netmute/dol/releases/download/v#{version}/dol_Linux_arm64.tar.gz"
      sha256 "74a1623cfdf31da41ca4364585efb4d65efed9ff103353714ba516276412508f"
    end
  end

  # No zap stanza required
end
