# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CtagsLsp < Formula
  desc "LSP implementation using universal-ctags as backend"
  homepage "https://github.com/netmute/ctags-lsp"
  version "0.2.2"

  depends_on "universal-ctags"

  on_macos do
    on_intel do
      url "https://github.com/netmute/ctags-lsp/releases/download/v0.2.2/ctags-lsp_Darwin_x86_64.tar.gz"
      sha256 "a8964523bdea256fd90fd8bdf550e3e22a88467736ce73ae69b6cd71c5461549"

      def install
        bin.install "ctags-lsp"
      end
    end
    on_arm do
      url "https://github.com/netmute/ctags-lsp/releases/download/v0.2.2/ctags-lsp_Darwin_arm64.tar.gz"
      sha256 "bbfe770a15b5262065dd9b55e2240ab6868276446c1dc4efb84058253e901904"

      def install
        bin.install "ctags-lsp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/netmute/ctags-lsp/releases/download/v0.2.2/ctags-lsp_Linux_x86_64.tar.gz"
        sha256 "34c9a8cde803470900c469e8ade13b332b95c52859cfad06d5febf0395a7c9b8"

        def install
          bin.install "ctags-lsp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/netmute/ctags-lsp/releases/download/v0.2.2/ctags-lsp_Linux_arm64.tar.gz"
        sha256 "0d450611f3eff28656e67f9aed98a6443e81da5414c0d1da5300abb8aff3fc1f"

        def install
          bin.install "ctags-lsp"
        end
      end
    end
  end
end
